#pragma once

int convertSynapErrorToMpiislError(int nErrorCode);
#define STATUS_CODE_ERR_PI_EXTRACT_FATAL				10000
#define STATUS_CODE_ERR_PI_EXTRACT_UNKNOWN				10001
#define STATUS_CODE_ERR_PI_EXTRACT_ENCRYPTED			10002
#define STATUS_CODE_ERR_PI_EXTRACT_UNSUPPORTED_VERSION	10003
#define STATUS_CODE_ERR_PI_EXTRACT_UNKNOWN_FORMAT		10004
#define STATUS_CODE_ERR_PI_EXTRACT_DRM					10005
#define STATUS_CODE_ERR_PI_EXTRACT_BAD_FILE				10006

#define MPIISL_ERROR_EXTRACTION_FATAL					STATUS_CODE_ERR_PI_EXTRACT_FATAL
#define MPIISL_ERROR_EXTRACTION_UNKNOWN					STATUS_CODE_ERR_PI_EXTRACT_UNKNOWN
#define MPIISL_ERROR_EXTRACTION_ENCRYPTED				STATUS_CODE_ERR_PI_EXTRACT_ENCRYPTED
#define MPIISL_ERROR_EXTRACTION_UNSUPPORTED_VERSION		STATUS_CODE_ERR_PI_EXTRACT_UNSUPPORTED_VERSION
#define MPIISL_ERROR_EXTRACTION_UNKNOWN_FORMAT			STATUS_CODE_ERR_PI_EXTRACT_UNKNOWN_FORMAT
#define MPIISL_ERROR_EXTRACTION_DRM						STATUS_CODE_ERR_PI_EXTRACT_DRM
#define MPIISL_ERROR_EXTRACTION_BAD_FILE				STATUS_CODE_ERR_PI_EXTRACT_BAD_FILE